# Generated by Django 5.0.1 on 2025-03-31 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('velo', 'Vélo'), ('moto', 'Moto'), ('voiture', 'Voiture')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
