# Generated by Django 5.0.1 on 2025-04-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shippingaddress_latitude_shippingaddress_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='longitude',
        ),
    ]
